name: PDF to TXT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr libtesseract-dev tesseract-ocr-lit
          pip install pymupdf pytesseract pillow

      - name: Run PDF Conversion Script
        run: python pdf.py

      - name: Upload output.txt
        uses: actions/upload-artifact@v3
        with:
          name: output-txt
          path: output.txt
